#!/bin/bash

temp_directory="/tmp/PrinterConfig"
target_printer=$(defaults read ${temp_directory}/PrinterConfig.plist NAME)
printer_location=$(defaults read ${temp_directory}/PrinterConfig.plist LOCATION)
printer_address=$(defaults read ${temp_directory}/PrinterConfig.plist ADDRESS)
driver=$(defaults read ${temp_directory}/PrinterConfig.plist DRIVER)
ppd="${temp_directory}/*.ppd"
package="${temp_directory}/*.pkg"
driver_test=`lpinfo -m -h 127.0.0.1:631 | grep "${driver}"`

if [ -z "$driver_test" ]; then
    sudo installer -pkg $package -target /
fi

lpadmin -p $target_printer \
    -L $printer_location \
    -v $printer_address \
    -o printer-is-shared=false \
    -P $ppd \
    -E

rm -rf $temp_directory
