#!/bin/bash

target_printer=$(defaults read /tmp/PrinterConfig/PrinterConfig.plist NAME)

printers=`lpstat -p | grep printer | cut -d" " -f2`
for printer in $printers;
do
    if [ "$printer" == $target_printer ]; then
        lpadmin -x $target_printer
    fi
done
